# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:title
# relative_permalinks: true

# Setup
title:               Gabriel
tagline:             ''
description:         'Olá, me chamo Gabriel Napoleão. Sou um Front End Developer de SP e um entusiasta Open Source. Ficarei muito feliz em você poder dá uma olhada nos meus posts e desse um feedback pelos comentários.' #'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://whoamindx.github.io
baseurl:             ''
paginate:            5

# contacts
contacts:
  facebook: https://facebook.com/whoamindx
  instagram: https://www.instagram.com/whoamindx/
  github: https://github.com/whoamindx
  email: whoamindx@gmail.com
  twitter: https://twitter.com/whoamindx
  linkedin: https://www.linkedin.com/in/whoamindx/
  # googleplus:
  spotify: https://open.spotify.com/user/whoamindx

# Custom vars
version:             1.0.0
